### PR TITLE
Fix bracket bug. #2648

### LINKED ISSUE #2648: Problem when searching strings with "(" or ")"
**Describe the bug**
The search does not work when the search string contains '(' or ')' characters.

**To Reproduce**
Steps to reproduce the behaviour:
1. [[Go to 'https://fairsharing.org/...'](https://fairsharing.org/search)](https://fairsharing.org/search)
2. Select in the left column any term that contains parenthesis characters, e.g. Organisations: "Austrian Science Fund (fwf)": https://fairsharing.org/search?organisations=austrian%2520science%2520fund%2520%28fwf%29%252C%2520austria&page=1 
or User Defined Tag (UDT) "High Performance Computing (hpc)" https://fairsharing.org/search?page=1&userDefinedTags=high%2520performance%2520computing%2520%28hpc%29
4. The search is empty when there are records, e.g. https://fairsharing.org/organisations/154 for the organisation and https://fairsharing.org/1403 for the UDT 
5. The same used to happen with Taxonomies, however, there are not longer taxonomies with "(". Anyway, I can infer that this happen with any field that contains any of these characters. I ignore if the same thing happens with any other non-aphabetic character. Anyway, the advanced search does not have this issue https://fairsharing.org/advancedsearch?operator=_and&fields=%28operator%3D_and%26organisations%3DAustrian%20Science%20Fund%20%28FWF%29,%20Austria%29 
6. There are more than 585 organisations that contain "(" or ")" in the name (curation problem as there is a filed for additional name  @allysonlister?) There are 17 UDT with "(" or ")"

### PR DESCRIPTION
**Pull request by knirirr**
It's not clear why some strings aren't being quoted if they contain brackets, but I have written code to add them to an array if detected which can work around the problem.

### CODE REVIEW

**Review by ramGranell — COMMENTED** [review]
When checking the organisations with parenthesis "Austrian Science Fund (fwf), Asutria" it keeps not returning anything:
 https://deploy-preview-2649--fairsharing.netlify.app/search?page=1&organisations=austrian%2520science%2520fund%2520%28fwf%29%252C%2520austria

when there are three records linked to it as it can be seen here: https://deploy-preview-2649--fairsharing.netlify.app/organisations/154

The case of High performance computing works properly: https://deploy-preview-2649--fairsharing.netlify.app/search?userDefinedTags=high%2520performance%2520computing%2520%28hpc%29&page=1

Other organistion with parenthesis works https://deploy-preview-2649--fairsharing.netlify.app/search?organisations=european%2520union%2520%28eu%29&page=1 Is it possible that it fails as it has parenthesis and comma as your code does a split by comma?

**Comment by knirirr** [comment]
>  Is it possible that it fails as it has parenthesis and comma as your code does a split by comma?

Possibly. I can remove that but who knows what other weird issues may crop up later?

File: src/store/recordSearch.js [hunk 1]
```diff
@@ -93,8 +93,17 @@ export const actions = {
     this.commit("records/setLoadingStatus", true);
     this.commit("records/resetRecords");
     this.commit("records/resetPages");
-    // params['q'] needs to be sanitised here.
     if (Object.keys(params).length > 0) {
+      // attempt to fix single fields with brackets, as per:
+      // https://github.com/FAIRsharing/fairsharing.github.io/issues/2648
+      Object.keys(params).forEach((key) => {
+        if (String(params[key]).includes('(') || String(params[key]).includes(')')) {
```
Comment (prakhyatox) [inline src/store/recordSearch.js:100]: If possible could you please try ```params[key] = [params[key]]```, instead of creating an array variable and pushing and assigning

**Review by ramGranell — APPROVED** [review]
All seems now to work properly
